@startuml eliminarDocente
skinparam linetype polyline

state eliminarDocente as "eliminarDocente()" {

    state " " as ConfirmandoEliminacion
    state " " as EliminandoDocente
    
    [*] -[#green]-> ConfirmandoEliminacion
    note on link
    <b>Administrador institucional</b> solicita eliminar docente
    end note
    
    ConfirmandoEliminacion -[#green]-> EliminandoDocente
    note on link
    <b>Sistema</b> presenta información del alumno a eliminar
    • Nombre
    • Apellidos
    • DNI 
    • nombre de usuario
    • Email 
    • Password 
    
    • Presenta advertencia de eliminación
    • Permite solicitar confirmar eliminación
    • Permite solicitar cancelar eliminación
    end note
    
    EliminandoDocente -[#green]-> [*]
    note on link
    <b>Administrador institucional</b> solicita confirmación de eliminación
    <b>Sistema</b> confirma eliminación
    end note
}

DOCENTES_ABIERTO -[#green]-> eliminarDocente

eliminarDocente -[#green]-> DOCENTES_ABIERTO
note on link
lista actualizada
end note

eliminarDocente -[#blue]-> DOCENTES_ABIERTO
note on link
cancelar eliminación
end note

@enduml