@startsalt
{+
  <b>EXPORTAR PREGUNTAS</b>
  
  
  {^" Sistema: Operación Completada "
    <color:green><b>¡Preguntas exportadas con Éxito!</b></color>
    ....
    [ Aceptar y Salir ]
  }
}
@endsalt