@startuml

class Examen{
 - evaluación
 - clave corrección
}
class AsignaturaGrado{
}
class Asignatura{
 - título
 - código
}
class Tema{
 - título
}
class Pregunta{
 - enunciado
 - opciones respuesta
 - respuesta correcta
 - dificultad
}
class BateriaDePreguntas{
}
class ModeloCorrección{
 - soluciones
}
class Grado{
 - título
 - código
}
class Profesor{
 - nombre
 - apellidos
 - DNI
}
class Alumno{
 - nombre
 - apellidos
 - DNI
}

Grado *-- Alumno : se matricula
Grado --* AsignaturaGrado : contiene
Asignatura --* AsignaturaGrado : contiene
Asignatura *-- Profesor : tiene asignado
Asignatura *-- Alumno : se imparte
Examen --* Asignatura : tiene
Examen *-- Pregunta : contiene
Asignatura *-- Tema : contiene
Tema *-- Pregunta : tiene
Alumno o-- Examen : realiza
BateriaDePreguntas *-- Pregunta : contiene
Examen *-- ModeloCorrección : se corrige
Profesor *-- BateriaDePreguntas : tiene
Profesor o-- Pregunta : crea
@enduml