@startuml

class Examen{
 - evaluacion
}
class Asignatura{
 - nombre
 - codigo
}
class Tema{
 - nombre
}
class Pregunta{
 - enunciado
 - opciones respuesta
 - respuesta correcta
 - dificultad
}
class BateriaDePreguntas
class ModeloCorrección
class Grado
class Universidad
class Profesor{
 - nombre
 - apellidos
 - DNI
}
class Alumno{
 - nombre
 - apellidos
 - DNI
}

Universidad --* Grado : tiene
Universidad --o Profesor : tiene
Grado o-- Alumno : matricula
Grado --o Asignatura : contiene
Asignatura --o Profesor : tiene asignado
Asignatura o-- Alumno : cursa
Examen *-- Asignatura : tiene
Examen --o Pregunta : contiene
Asignatura --* Tema : contiene
Tema *-- Pregunta : forma parte
Alumno --o Examen : realiza
BateriaDePreguntas *-- Pregunta : forma parte
Examen --* ModeloCorrección : tiene
Asignatura --o BateriaDePreguntas : tiene
Profesor --o Pregunta : crea
@enduml
