@startuml

class Examen{
 - evaluación
 - clave corrección
}
class Asignatura{
 - título
 - código
}
class Pregunta{
 - asignatura
 - tema
 - enunciado
 - opciones respuesta
 - respuesta correcta
 - dificultad
}
class BateriaDePreguntas{
}
class ModeloCorrección{
 - orden concreto de soluciones
}
class Grado{
 - título
 - código
}
class Profesor{
 - nombre
 - apellidos
 - DNI
}
class Alumno{
 - nombre
 - apellidos
 - DNI
}
enum EvaluaciónExamen{
 - Parcial 1
 - Parcial 2
 - Parcial 3
 - Examen final
 - Examen extraordinario
}
enum DificultadPregunta{
 - facil
 - medio
 - dificil
}

Examen .. EvaluaciónExamen
Pregunta -u-* Examen : contiene
Pregunta .. DificultadPregunta
Examen *-r- ModeloCorrección : se corrige
Profesor o-l- Pregunta : crea
Profesor *-u- Examen : crea
Asignatura *-- BateriaDePreguntas : tiene
BateriaDePreguntas *-u- Pregunta : contiene
Asignatura *-u- Examen : tiene 
Asignatura o-l- Profesor : tiene  
Grado *-u- Asignatura: contiene 
Alumno o-u- Examen : realiza 
Asignatura *-r- Alumno : se imparte 
Grado *-u- Alumno : se cursa

@enduml