@startuml

title Diagrama de Estados - Entidad Pregunta

state "No Creado" as no_creado 
state "En Construcción" as construccion 
state "Habilitada" as habilitada
state "Inhabilitada" as inhabilitada 

[*] --> no_creado

no_creado --> construccion : Crear
construccion --> habilitada : Habilitar

habilitada --> inhabilitada : Deshabilitar
inhabilitada --> habilitada : Habilitar

habilitada --> [*] : Finalizar
inhabilitada --> [*] : Finalizar

@enduml