@startsalt exportarGrados_WIREFRAME
{+
    <b>EXPORTAR GRADOS</b>
    ===
    .
    <b>1. Selección Actual</b>
    <i>Ha seleccionado 3 titulaciones para exportar.</i>
    .
    {#
        <b>Código</b> | <b>Título</b> | <b>Año</b>
        G-INF | Grado en Ing. Informática | 2024-2025
        G-MED | Grado en Medicina | 2024-2025
        M-DS  | Máster en Data Science | 2024-2025
    }
    .
    [ <&pencil> Editar selección (Volver atrás) ]
    .
    --
    .
    <b>2. Configuración de Exportación</b>
    Formato de salida:
    (o) Excel (.xlsx) - Estructurado
    ( ) CSV (Texto plano)
    ( ) XML (Integración con otros sistemas)
    .
    Opciones de datos:
    [X] Incluir estructura de asignaturas
    [ ] Incluir metadatos de coordinadores
    .
    ====
    .
    "Confirmación del proceso:"
    { [ X Cancelar ] | [ ^Exportar Grados^ ] }
}
@endsalt