@startsalt
{
    {^" Menú Principal "
        .
        [Gestionar Docentes                    ]
        [Cerrar Sesión                         ]
        .
    }
    ====
    Usuario: AdministradorInstitucional
    ====
}
@endsalt