@startsalt
{
    {^" Menú Principal "
        .
        [Gestionar Grados                      ]
        [Gestionar Asignaturas                 ]
        [Gestionar Alumnos                     ]
        [Gestionar Preguntas                   ]
        [Generar Exámenes                      ]
        [Corregir Exámenes                     ]
        [Importar Configuracion Global         ]
        [Exportar Configuracion Global         ]
        [Cerrar Sesión                         ]
        .
    }
    ====
    Usuario: Docente
    ====
}
@endsalt