@startsalt crearPregunta_FORMULARIO
{
    <b>CREAR NUEVA PREGUNTA</b>
    ===
    {
        <b>1. Configuración del enunciado</b>
        --
        {
            Asignatura: | "Programación I (Preseleccionada)"
            Enunciado (*): | {S "Escriba aquí el enunciado de la pregunta...      "
                                "                                              "}
            Tema:          | ^Seleccionar Tema^
            Dificultad:    | ^Medio^
        }
        
        --
        <b>2. Definición de Respuestas</b>
        <i>Rellene las opciones y marque la correcta</i>
        {
            ( ) Correcta | Option A: | "                          "
            (X) Correcta | Option B: | "Respuesta correcta ejemplo"
            ( ) Correcta | Option C: | "                          "
            ( ) Correcta | Option D: | "                          "
            . | [ + Añadir otra opción ]
        }

        ~~
        .
        {[Guardar Pregunta] | [Cancelar]}
    }
}
@endsalt