@startuml
title Diagrama de Estados - Entidad Examen

[*] --> NoCreado : iniciar
NoCreado --> Creado : generar
Creado --> Asignado : asignar
Asignado --> Corregido : corregir
Corregido --> [*] : finalizar

@enduml
