@startuml actoresYCasosDeUso-docente

left to right direction

actor "Docente" as doc

package "Módulo Grado" {
  usecase "crearGrado()" as UC1
  usecase "verGrados()" as UC2
  usecase "editarGrado()" as UC3
  usecase "eliminarGrado()" as UC4
}

package "Módulo Asignatura" {
  usecase "crearAsignatura()" as UC5
  usecase "verAsignaturas()" as UC6
  usecase "editarAsignatura()" as UC7
  usecase "eliminarAsignatura()" as UC8
}

package "Módulo Alumno" {
  usecase "crearAlumno()" as UC9
  usecase "verAlumnos()" as UC10
  usecase "editarAlumno()" as UC11
  usecase "eliminarAlumno()" as UC12
   usecase "importarAlumnos()" as UC19
   usecase "exportarAlumnos()" as UC17
}



package "Módulo Gestión de Preguntas" {
  usecase "crearPregunta()" as UC20
  usecase "verPreguntas()" as UC21
  usecase "editarPregunta" as UC22
  usecase "eliminarPregunta()" as UC23
  usecase "importarPreguntas()" as UC24
  usecase "exportarPreguntas()" as UC25
 usecase "crearRespuesta()" as UC32
  usecase "verRespuestas()" as UC33
  usecase "editarRespuesta()" as UC34
  usecase "eliminarRespuesta()" as UC35
}

package "Módulo Configuración General" {
  usecase "exportarConfiguracionGlobal()" as UC26
  usecase "importarConfiguracionGlobal()" as UC27
}

package "Módulo Examen" {
  usecase "generarExamenes()" as UC28
  usecase "asignarExamenes()" as UC29
 
}

package "Módulo Corrección" {
  usecase "corregirExamenes()" as UC31
}

package "Módulo Sesión" {
  usecase "iniciarSesion()" as UC41
  usecase "cerrarSesion()" as UC42
}

package "Módulo Gestión" {
  usecase "completarGestion()" as UC13

}

doc --> UC1
doc --> UC2
doc --> UC3
doc --> UC4
doc --> UC5
doc --> UC6
doc --> UC7
doc --> UC8
doc --> UC9
doc --> UC10
doc --> UC11
doc --> UC12
doc --> UC13
doc --> UC17
doc --> UC19
doc --> UC20
doc --> UC21
doc --> UC22
doc --> UC23
doc --> UC24
doc --> UC25
doc --> UC26
doc --> UC27
doc --> UC28
doc --> UC29
doc --> UC31
doc --> UC32
doc --> UC33
doc --> UC34
doc --> UC35
doc --> UC41
doc --> UC42

@enduml
