@startuml actoresYCasosDeUso-completo

left to right direction

actor "Docente" as doc
actor "Administrador Institucional" as admin
actor "Tiempo" as tiempo

package "Módulo Grado" {
  usecase "Crear grado" as UC1
  usecase "Ver grados" as UC2
  usecase "Editar grado" as UC3
  usecase "Eliminar grado" as UC4
}

package "Módulo Asignatura" {
  usecase "Crear asignatura" as UC5
  usecase "Ver asignaturas" as UC6
  usecase "Editar asignatura" as UC7
  usecase "Eliminar asignatura" as UC8
}

package "Módulo Alumno" {
  usecase "Crear alumno" as UC9
  usecase "Ver alumnos" as UC10
  usecase "Editar alumno" as UC11
  usecase "Eliminar alumno" as UC12
  usecase "Importar alumnos" as UC19
}

package "Módulo Asignaciones" {
  usecase "Actualizar alumno de grado" as UC13
  usecase "Actualizar grado de asignatura" as UC15
  usecase "Actualizar alumno de asignatura" as UC17
}

package "Módulo Gestión de Preguntas" {
  usecase "Crear pregunta" as UC20
  usecase "Ver preguntas" as UC21
  usecase "Ver pregunta" as UC30
  usecase "Editar pregunta" as UC22
  usecase "Eliminar pregunta" as UC23
  usecase "Importar preguntas" as UC24
  usecase "Exportar preguntas" as UC25
}

package "Módulo Configuración General" {
  usecase "Exportar configuración global" as UC26
  usecase "Importar configuración global" as UC27
}

package "Módulo Examen" {
  usecase "Crear examenes" as UC28
  usecase "Asignar examenes" as UC29
}

package "Módulo Corrección" {
  usecase "Corregir exámenes" as UC31
}

package "Módulo Usuarios Docentes" {
  usecase "Crear profesor" as UC32
  usecase "Ver profesores" as UC33
  usecase "Editar profesor" as UC34
  usecase "Eliminar profesor" as UC35
}

package "Módulo Gestión Licencias(intencion)" {
  usecase "Adquirir licencia" as UC36
  usecase "Ver licencias" as UC37
  usecase "Editar licencia" as UC38
  usecase "Eliminar licencia" as UC39
}

package "Módulo Sesión" {
  usecase "Cerrar sesión automáticamente" as UC40
  usecase "Iniciar sesión" as UC41
  usecase "Cerrar sesión" as UC42
}

doc --> UC1
doc --> UC2
doc --> UC3
doc --> UC4
doc --> UC5
doc --> UC6
doc --> UC7
doc --> UC8
doc --> UC9
doc --> UC10
doc --> UC11
doc --> UC12
doc --> UC13
doc --> UC15
doc --> UC17
doc --> UC19
doc --> UC20
doc --> UC21
doc --> UC22
doc --> UC23
doc --> UC24
doc --> UC25
doc --> UC26
doc --> UC27
doc --> UC28
doc --> UC29
doc --> UC31
doc --> UC41
doc --> UC42

admin --> UC32
admin --> UC33
admin --> UC34
admin --> UC35
admin --> UC36
admin --> UC37
admin --> UC38
admin --> UC39
admin --> UC41
admin --> UC42

tiempo --> UC40

@enduml