@startuml
skinparam linetype polyline

state RESPUESTAS_ABIERTO
state RESPUESTAS_CONTEXTUALES_ABIERTO
state PREGUNTAS_ABIERTO
state PREGUNTAS_CONTEXTUALES_ABIERTO
state PREGUNTA_ABIERTO
state PREGUNTA_CONTEXTUAL_ABIERTO

RESPUESTAS_ABIERTO -[#green]-> editarPregunta
RESPUESTAS_CONTEXTUALES_ABIERTO -[#green]-> editarPregunta
PREGUNTAS_ABIERTO -[#green]-> editarPregunta
PREGUNTAS_CONTEXTUALES_ABIERTO -[#green]-> editarPregunta
PREGUNTA_ABIERTO -[#green]-> editarPregunta
PREGUNTA_CONTEXTUAL_ABIERTO -[#green]-> editarPregunta

state editarPregunta as "editarPregunta()" {

    state " " as EditandoDatos
    state " " as GuardandoDatos 

    [*] -[#green]-> EditandoDatos 
    note on link
    <b>Docente</b> solicita editar
    end note    
    
    EditandoDatos -[#green]-> GuardandoDatos
    note on link
    <b>Sistema</b> presenta datos de edición
    
    • Asignatura, Enunciado
    • Tema, Dificultad (Enum)
    • Respuestas (contenido y si es correcta/incorrecta)
    • Habilitada/deshabilitada

    <b>Sistema</b> permite solicitar:
    • modificar campos
    • guardar pregunta
    • cancelar edición
    end note
    
    GuardandoDatos -[#green]-> EditandoDatos
    note on link
    <b>Docente</b> solicita modificar campos
    end note
    
    GuardandoDatos -[#green]-> [*]
    note on link
    <b>Docente</b> solicita guardar y salir
    end note

    GuardandoDatos -[#red]-> [*]
    note on link
    <b>Docente</b> solicita cancelar edición
    end note
}

' 3. Transiciones DE SALIDA desde editarPregunta

editarPregunta -[#green]-> PREGUNTA_ABIERTO


editarPregunta -[#green]-> PREGUNTA_CONTEXTUAL_ABIERTO


' Salida de cancelación (Opcional: regresa a la lista general o al origen)
editarPregunta -[#red]-> PREGUNTAS_ABIERTO : Cancelar

editarPregunta -[#red]-> PREGUNTAS_CONTEXTUALES_ABIERTO : Cancelar

@enduml