@startuml
title Diagrama de Estados - Entidad Examen

 [*] --> Creado : generar
 Creado --> Asignado : asignar
 Asignado --> Resuelto : alumnos realizan el examen
 Resuelto --> Corregido : corregir

@enduml
