@startsalt abrirProfesores-wireframe
{ 
<b>GESTIÓN DE ALUMNOS</b>  
===
{+  DNI | NOMBRE | APELLIDOS | ACCIÓN
  --|--|--|--
  12345678A | Roberto | Sánz Roca | [Editar]
  87654321B | Raúl | González Gurruchaga | [Editar]  
 PXYZ | Nombre del alumno | Apellidos del alumno | [Editar]
  }
  ~~
  {<b>BUSCAR:</b> [                                      ] | [Filtrar]}
  ~~
  { [Crear nuevo] | [Borrar seleccionado] | [Importar] | [Exportar] | . | [Salir] }
}
@endsalt