@startsalt cancelarGeneracion_WIREFRAME
{+
    <b>GENERACIÓN DE EXÁMENES | <b>VISTA PREVIA</b>
    Asignatura: <b>Estructura de Datos (GII-24)</b> | Fecha: <b>12/12/2024</b>
    ===
    .
    Generación completada. 
    .
    {#
        <b>ID</b> | <b>Tipo</b> | <b>Preguntas</b>
        EX-01 | Parcial 1 | 10 Preguntas
        EX-02 | Parcial 1 | 10 Preguntas
        EX-03 | Parcial 1 | 10 Preguntas
    }
    .
    {
        ¿Está seguro que desea cancelar la generación actual?
        .
        <color:red><b>⚠ ADVERTENCIA:</b></color>
        Si confirma la cancelación, los 3 exámenes generados en esta sesión se perderán.
        .
        ---
        .
        [ <b>No cancelar</b> ] | [ <b>Cancelar generación</b> ]
    }
    .
    .
}
@endsalt